// Belgian datalist suggestions — common values so typing goes faster.

export const fuelStations = [
  'Q8 Herentals',
  'Q8 Antwerpen',
  'Total Herentals',
  'Total Energies',
  'Esso',
  'Shell',
  'Lukoil',
  'Dats 24',
  'Octa+',
  'G&V',
  'Argenta',
  'Gabriels',
  'Tinq',
]

export const maintenanceTypes = [
  'Olie verversen',
  'Oliefilter',
  'Luchtfilter',
  'Brandstoffilter',
  'Interieurfilter (pollenfilter)',
  'Remblokken vooraan',
  'Remblokken achteraan',
  'Remschijven vooraan',
  'Remschijven achteraan',
  'Remvloeistof',
  'Bougies',
  'Distributieriem',
  'Distributieketting',
  'Accu vervangen',
  'Banden wisselen (zomer)',
  'Banden wisselen (winter)',
  'Uitlijning',
  'Koelvloeistof',
  'Ruitenwissers',
  'Grote onderhoudsbeurt',
  'Kleine onderhoudsbeurt',
  'Technische keuring',
  'APK / autokeuring',
  'Airco onderhoud',
  'Versnellingsbakolie',
]

export const garages = [
  'Ford Herentals',
  'D\u2019Ieteren',
  'Alcopa',
  'Euro Repar',
  'Carglass',
  'Feu Vert',
  'ATU',
  'Local garage',
]

export const modificationBrands = [
  'Maxton Design',
  'OZ Racing',
  'Eibach',
  'K&N',
  'Bilstein',
  'H&R',
  'Milltek',
  'Akrapovi\u010d',
  'Borla',
  'Brembo',
  'BBS',
]

export const belgianCities = [
  'Herentals',
  'Antwerpen',
  'Brussel',
  'Leuven',
  'Gent',
  'Mechelen',
  'Turnhout',
  'Hasselt',
  'Brugge',
  'Kortrijk',
  'Namen',
  'Luik',
  'Durbuy',
  'Spa',
  'Knokke',
  'Oostende',
]
